# Release Metadata
release:
  name: OpenShift GitOps Operator
  version: "99.99.99"
  olm:
    # TODO: Compute olm data automatically
    channel: "latest,gitops-99.99"
    replaces: "openshift-gitops-operator.v99.99.98"
    skip-range: "" # empty for z-stream & ">=1.0.0 <x.y.0" for y-stream
  konflux:
    repo: https://github.com/rh-gitops-midstream/release.git
    branch: main
    application: gitops-main
  managers:
    - name: "Siddhesh Ghadi"
      github: svghadi
      email: "sghadi@redhat.com"

# Source code repositories
# This section defines the source repositories for GitOps Operator artifacts built from source.
# See docs/sources.md for details on each field and usage instructions.
# On update, run `make sources` to update & validate the submodules.
# Note: `commit` is always used to perform the actual checkout. `ref` is purely metadata for CI which can be a tag or branch.
sources:
  - path: sources/argo-cd
    url: https://github.com/argoproj/argo-cd.git
    ref: v2.14.15
    commit: 6c7d6940cd19a4543e749d18ac282c7020c7c92e