apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: buildah-from-containerfile
spec:
  params:
  - name: image
    description: The URL of the image to build and push.
  - name: context
    description: The path to the build context.
    default: "."
  workspaces:
  - name: source
  results:
  - name: IMAGE_URL
    description: The URL of the pushed image.
  - name: IMAGE_DIGEST
    description: The digest of the pushed image.
  steps:
  - name: build-and-push
    image: quay.io/buildah/stable:v1.33
    workingDir: $(workspaces.source.path)
    script: |
      buildah bud \
        -t "$(params.image)" \
        -f "$(params.context)/Dockerfile" "$(params.context)"
      
      buildah push \
        --digestfile "$(results.IMAGE_DIGEST.path)" \
        "$(params.image)" \
        "docker://$(params.image)"
      
      echo -n "$(params.image)" | tee "$(results.IMAGE_URL.path)"