apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: generate-spec-file
spec:
  description: This task runs a preparation script inside a custom tool image
    to generate a final .spec file.
  params:
  - name: TOOL_IMAGE
    description: The URL of the tool image to use for generating the .spec file.
  - name: PATH_CONTEXT
    description: The path to the working directory.
    default: "."
  workspaces:
  - name: source
    description: A workspace containing the source code.
  steps:
  - name: generate-spec
    image: $(params.TOOL_IMAGE)
    workingDir: $(workspaces.source.path)/$(params.PATH_CONTEXT)
    script: |
      #!/usr/-bin/env bash
      set -euxo pipefail
      
      # This runs the script from your repository to generate the .spec file
      /workspace/pre-build-script.sh
      
      echo "SUCCESS: microshift-gitops.spec file generated."