apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/nmirasch/konflux-components-testing?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch
      == "main"
  labels:
    appstudio.openshift.io/application: test-rpms-builds
    appstudio.openshift.io/component: microshift-gitops-rpm
    pipelines.appstudio.openshift.io/type: build
  name: microshift-gitops-rpm-on-push
  namespace: nmirasch-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/nmirasch-tenant/microshift-gitops-builder:{{revision}}
  - name: additional-tags
    value:
    - '{{target_branch}}'
  - name: dockerfile
    value: Containerfile
  - name: prefetch-input
    value: '[{"type": "gomod", "path": "./sources/tools"}]'
  - name: git-metadata-directories
    value:
    - sources/tools
  pipelineRef:
    name: build-multi-platform-image
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}