apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/nmirasch/konflux-components-testing?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch
      == "main"
      )
  labels:
    appstudio.openshift.io/application: test-rpms-builds
    appstudio.openshift.io/component: microshift-gitops-rpm
    pipelines.appstudio.openshift.io/type: build
  name: microshift-gitops-rpm-on-pull-request
  namespace: nmirasch-tenant
spec:
  params:
  # Parameters for the final RPM artifact
  - name: ociStorage
    value: quay.io/redhat-user-workloads/nmirasch-tenant/microshift-gitops-rpm:{{revision}}
  - name: package-name
    value: microshift-gitops
  
  # Git parameters
  - name: git-url
    value: "{{ source_url }}"
  - name: revision
    value: "{{ revision }}"
  - name: target-branch
    value: "{{ target_branch }}"
  
  # New parameter for the temporary tools image
  - name: tool-image-url
    value: quay.io/redhat-user-workloads/nmirasch-tenant/microshift-gitops-builder:{{revision}}
  
  # General parameters
  - name: path-context
    value: "."
  - name: hermetic
    value: "true"
  
  pipelineRef:
    resolver: git
    params:
    - name: url
      value: "{{ source_url }}"
    - name: revision
      value: "{{ revision }}"
    - name: pathInRepo
      value: .tekton/pipeline.yaml # This points to your new all-in-one pipeline
  workspaces:
  - name: source
    persistentVolumeClaim:
      claimName: "{{pvc_name}}"
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'