apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: custom-rpm-build-pipeline
spec:
  # Parameters for the entire workflow
  params:
  - name: git-url
  - name: revision
  - name: tool-image-url
  - name: path-context
    default: "."
  - name: package-name
  - name: ociStorage
  - name: target-branch
  - name: hermetic
    default: "false"
  
  # Workspaces shared across tasks
  workspaces:
  - name: source
  - name: git-auth
  
  tasks:
  # Task 1: Clone the repository
  - name: git-clone
    taskRef:
      resolver: hub
      params:
      - name: name
        value: git-clone
      - name: kind
        value: task
      - name: version
        value: "0.9"
    workspaces:
    - name: output
      workspace: source
    - name: basic-auth
      workspace: git-auth
    params:
    - name: url
      value: $(params.git-url)
    - name: revision
      value: $(params.revision)
  
  # Task 2: Build your tools image from the Dockerfile
  - name: build-tools-image
    runAfter: [git-clone]
    workspaces:
    - name: source
      workspace: source
    params:
    - name: image
      value: $(params.tool-image-url)
    - name: context
      value: $(params.path-context)
    taskSpec:
      params:
      - name: image
      - name: context
      workspaces:
      - name: source
      results:
      - name: IMAGE_URL
      steps:
      - name: build-and-push
        image: quay.io/buildah/stable:v1.33
        workingDir: $(workspaces.source.path)
        script: |
          buildah bud -t "$(params.image)" -f "$(params.context)/Dockerfile" "$(params.context)"
          buildah push "$(params.image)" "docker://$(params.image)"
          echo -n "$(params.image)" | tee "$(results.IMAGE_URL.path)"
  
  # Task 3: Generate the .spec file using the tools image
  - name: generate-spec-file
    runAfter: [build-tools-image]
    workspaces:
    - name: source
      workspace: source
    params:
    - name: TOOL_IMAGE
      value: $(tasks.build-tools-image.results.IMAGE_URL)
    - name: PATH_CONTEXT
      value: $(params.path-context)
    taskSpec:
      params:
      - name: TOOL_IMAGE
      - name: PATH_CONTEXT
      workspaces:
      - name: source
      steps:
      - name: generate-spec
        image: $(params.TOOL_IMAGE)
        workingDir: $(workspaces.source.path)/$(params.PATH_CONTEXT)
        script: |
          #!/usr/bin/env bash
          set -euxo pipefail
          /workspace/pre-build-script.sh
          echo "SUCCESS: microshift-gitops.spec file generated."
  
  # Task 4: Call the remote Konflux pipeline to build the RPM
  - name: run-konflux-rpm-build
    runAfter: [generate-spec-file]
    pipelineRef:
      resolver: git
      params:
      - name: url
        value: "https://github.com/konflux-ci/rpmbuild-pipeline.git"
      - name: revision
        value: "main"
      - name: pathInRepo
        value: "pipeline/build-rpm-package.yaml"
    workspaces:
    - name: source
      workspace: source
    params:
    - name: git-url
      value: $(params.git-url)
    - name: revision
      value: $(params.revision)
    - name: package-name
      value: $(params.package-name)
    - name: ociStorage
      value: $(params.ociStorage)
    - name: target-branch
      value: $(params.target-branch)
    - name: hermetic
      value: $(params.hermetic)