apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: custom-rpm-build-pipeline
spec:
  params:
  - name: git-url
  - name: revision
  - name: tool-image-url
  - name: path-context
    default: "."
  - name: package-name
    description: The name of the package to build.
  - name: ociStorage
    description: The container registry where the final RPM artifact will be stored.
  - name: target-branch
    description: The target branch of the pull request.
  - name: hermetic
    description: Specifies whether the build should be hermetic.
    default: "false"
  
  workspaces:
  - name: source
  - name: git-auth
  
  tasks:
  - name: fetch-repository
    taskRef: { name: git-clone, kind: ClusterTask }
    workspaces:
    - name: output
      workspace: source
    params:
    - name: url
      value: $(params.git-url)
    - name: revision
      value: $(params.revision)
  
  # Task 2: Build your tools image (no changes here)
  - name: build-tools-image
    runAfter: [fetch-repository]
    workspaces:
    - name: source
      workspace: source
    params:
    - name: image
      value: $(params.tool-image-url)
    - name: context
      value: $(params.path-context)
    taskSpec:
      params:
      - name: image
      - name: context
      workspaces:
      - name: source
      results:
      - name: IMAGE_URL
      - name: IMAGE_DIGEST
      steps:
      - name: build-and-push
        image: quay.io/buildah/stable:v1.33
        workingDir: $(workspaces.source.path)
        script: |
          buildah bud \
            -t "$(params.image)" \
            -f "$(params.context)/Dockerfile" "$(params.context)"
          
          buildah push \
            --digestfile "$(results.IMAGE_DIGEST.path)" \
            "$(params.image)" \
            "docker://$(params.image)"
          
          echo -n "$(params.image)" | tee "$(results.IMAGE_URL.path)"
  
  # Task 3: Generate the .spec file
  - name: generate-spec-file
    runAfter: [build-tools-image]
    workspaces:
    - name: source
      workspace: source
    params:
    - name: TOOL_IMAGE
      value: $(tasks.build-tools-image.results.IMAGE_URL)
    - name: PATH_CONTEXT
      value: $(params.path-context)
    taskSpec:
      params:
      - name: TOOL_IMAGE
      - name: PATH_CONTEXT
      workspaces:
      - name: source
      steps:
      - name: generate-spec
        image: $(params.TOOL_IMAGE)
        workingDir: $(workspaces.source.path)/$(params.PATH_CONTEXT)
        script: |
          #!/usr/bin/env bash
          set -euxo pipefail
          /workspace/pre-build-script.sh
          echo "SUCCESS: microshift-gitops.spec file generated."
  
  # Task 4: Build the RPM using the official Konflux CI task
  - name: build-rpm-package
    runAfter: [generate-spec-file]
    workspaces:
    - name: source
      workspace: source
    taskRef:
      resolver: git
      params:
      - name: url
        value: "https://github.com/konflux-ci/rpmbuild-pipeline.git"
      - name: revision
        value: "main"
      - name: pathInRepo
        value: "task/rpmbuild.yaml"
    params:
    - name: package-name
      value: $(params.package-name)
    - name: ociStorage
      value: $(params.ociStorage)
    - name: target-branch
      value: $(params.target-branch)
    - name: hermetic
      value: $(params.hermetic)
    - name: PLATFORM
      value: "linux/amd64"
    - name: script-environment-image
      value: ""
    - name: dependencies-artifact
      value: ""
    - name: calculation-artifact
      value: ""
    - name: ociArtifactExpiresAfter
      value: ""