name: Update Spec File and Create PR

on:
  # This allows you to run the workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      gitops_version:
        description: 'ArgoCD version suffix'
        required: true
        default: '1.17.0-5'
      gitops_registry:
        description: 'ArgoCD container registry'
        required: true
        default: 'registry.redhat.io'
      gitops_image_name:
        description: 'ArgoCD image name'
        required: true
        default: 'openshift-gitops-1/argocd-rhel9'
      redis_registry:
        description: 'Redis container registry'
        required: true
        default: 'registry.redhat.io'
      redis_image_name:
        description: 'Redis image name'
        required: true
        default: 'rhel9/redis-7'
      redis_tag_prefix:
        description: 'Redis tag prefix to search for'
        required: true
        default: '9.6-1755009825'
      ci_x_version:
        description: 'CI X version component'
        required: true
        default: '1'
      ci_y_version:
        description: 'CI Y version component'
        required: true
        default: '17'
      ci_z_version:
        description: 'CI Z version component'
        required: true
        default: '0'
      ci_spec_release:
        description: 'CI Spec Release version'
        required: true
        default: '1.17'
      ci_argo_cd_upstream_tag:
        description: 'ArgoCD upstream source tag (without v)'
        required: true
        default: '3.0.12'
      target_branch:
        description: 'The branch to create the pull request against'
        required: true
        default: 'main'

jobs:
  update-spec-and-create-pr:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Git config
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
    
    - name: Install skopeo
      run: |
        sudo apt-get update
        sudo apt-get install -y skopeo podman
    
    - name: Log in to registry.redhat.io
      run: |
        mkdir -p ~/.config/containers
        podman login registry.redhat.io -u ${{ secrets.RH_USERNAME }} -p ${{ secrets.RH_PASSWORD }}
    
    - name: Run the Pre-Build Script
      # This step executes your script.
      # NOTE: Assumes your script is in a directory named 'scripts'.
      # Please adjust the 'working-directory' if your file is located elsewhere.
      id: run_script
      working-directory: ./rpms/microshift-gitops
      env:
        # Maps the workflow inputs to the environment variables your script uses
        GITOPS_VERSION: ${{ inputs.gitops_version }}
        GITOPS_REGISTRY: ${{ inputs.gitops_registry }}
        GITOPS_IMAGE_NAME: ${{ inputs.gitops_image_name }}
        REDIS_REGISTRY: ${{ inputs.redis_registry }}
        REDIS_IMAGE_NAME: ${{ inputs.redis_image_name }}
        REDIS_TAG_PREFIX: ${{ inputs.redis_tag_prefix }}
        CI_X_VERSION: ${{ inputs.ci_x_version }}
        CI_Y_VERSION: ${{ inputs.ci_y_version }}
        CI_Z_VERSION: ${{ inputs.ci_z_version }}
        CI_SPEC_RELEASE: ${{ inputs.ci_spec_release }}
        CI_ARGO_CD_UPSTREAM_TAG: ${{ inputs.ci_argo_cd_upstream_tag }}
      run: ./generic-pre-build-script.sh
    
    - name: Create Pull Request
      # This action checks for changes and creates a PR if any are found.
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "feat: Update container image digests and versions"
        title: "Automated Spec File Update for ArgoCD & Redis"
        body: |
          This PR was automatically generated by the 'Update Spec File' GitHub Action.
          
          It updates the container image digests and versions based on the following inputs:
          - **ArgoCD Version**: `${{ inputs.gitops_version }}`
          - **Redis Tag Prefix**: `${{ inputs.redis_tag_prefix }}`
          - **ArgoCD Upstream Tag**: `${{ inputs.ci_argo_cd_upstream_tag }}`
          
          Please review the changes to `microshift-gitops.spec` and merge.
        branch: "bot/update-spec-${{ github.run_id }}"
        delete-branch: true
        base: ${{ inputs.target_branch }}
        author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
        committer: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
